[[news]]
date = "2026-01"
content = "Pass M.S. defense (Master-Along-the-Way for PhD program)." 

[[news]]
date = "2025-05"
content = "Awarded PSU CSE Best Research Assistant 2025!"

[[news]]
date = "2025-05"
content = "One paper accepted by ICML 2025."

[[news]]
date = "2025-03"
content = "AAAR-1.0 wins Best Paper Award at the 2nd AI4Research workshop @ AAAI 2025!"


[[news]]
date = "2024-01"
content = "Two papers ('MUFFIN' and 'Knowledge Conflict') accepted by ICLR 2024."

